version: "3.3"
services:
  # Main api
  api:
    build: .
    container_name: api
    command: npm run watch:dev
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      PORT: 3000
      JWT_SECRET: superSecret
      JWT_EXP: 7200000
      JWT_ALGORITHM: HS256

  # MySQL for API
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: "api_db"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db: {}
